#服务相关配置
server:
  port: 8083
  servlet:
    context-path: /
spring:
  # 应用名称
  application:
    name: alibaba-server-gateway
  cloud:
    nacos:
      # 指定注册中心的地址
      discovery:
        server-addr: 127.0.0.1:8848
    #网关配置
    gateway:
      routes:
        #id唯一就ok
        - id: server-provider
          # lb就是loadbance的意思，去注册中心找名字为 alibaba-server-provider的服务
          uri: lb://alibaba-server-provider
          # 匹配规则，路径匹配，只要路径是gateway开头的都会匹配上
          predicates:
            - Path=/gateway/**
          #截取规则，截掉第一级，既/gateway
          filters:
            - StripPrefix=1
      # 让gateway通过服务发现组件找到其他的微服务
      discovery:
        locator:
          enabled: true
